# Generated by Django 6.0.2 on 2026-02-24 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='whitelist',
            field=models.ManyToManyField(related_name='workplace_whitelist_granted', to=settings.AUTH_USER_MODEL),
        ),
    ]
