# Generated by Django 6.0.2 on 2026-02-23 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('observations', models.TextField()),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='merchants.workplace')),
            ],
        ),
    ]
