# Generated by Django 6.0.2 on 2026-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
