# Generated by Django 6.0.2 on 2026-02-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='merchants.workplace'),
        ),
    ]
