# Generated by Django 6.0.2 on 2026-03-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('merchants', '0004_alter_workplace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='merchants.workplace'),
        ),
    ]
