# Generated by Django 6.0.2 on 2026-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_route', 'On route'), ('delivered', 'Delivered'), ('issue', 'Issue'), ('in_preparation', 'In preparation')], default='pending', max_length=20),
        ),
    ]
