# Generated by Django 6.0.2 on 2026-03-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='workplace',
        ),
    ]
