# Generated by Django 6.0.2 on 2026-03-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_created_remove_orderitem_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_route', 'On route'), ('delivered', 'Delivered'), ('issue', 'Issue'), ('in_preparation', 'In preparation'), ('returned', 'Returned'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
    ]
