# Generated by Django 6.0.2 on 2026-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_workplace_owner'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('workplace', 'sku')},
        ),
        migrations.DeleteModel(
            name='ProductsTransactions',
        ),
    ]
